project:
  type: website
  output-dir: docs

website:
  title: "pa-blog (statistics stuff for you and for me)"
  site-url: https://pablogregori.github.io/pa-blog/
  description: "A blog my stats and R ideas"
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



